import React, { useState, useEffect, useRef } from 'react';
import { Search, MoreVertical, Send, CheckCheck, Check, Sparkles } from 'lucide-react';

export default function ChatWindow({ persona, onSendMessage, showDashboard, onToggleDashboard }) {
  const [inputText, setInputText] = useState('');
  const messagesEndRef = useRef(null);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [persona?.chatHistory]);

  if (!persona) {
    return (
      <div className="chat-area" style={{ alignItems: 'center', justifyContent: 'center', display: 'flex', flexDirection: 'column', gap: 14 }}>
        <div style={{ fontSize: 40 }}>🤖</div>
        <h2 style={{ margin: 0, fontSize: 16, fontWeight: 700, color: '#1e1b4b' }}>Select a persona to chat</h2>
        <p style={{ margin: 0, fontSize: 12, color: '#94a3b8', textAlign: 'center', maxWidth: 280, lineHeight: 1.6 }}>
          Choose a contact from the sidebar to start chatting with their digital clone.
        </p>
      </div>
    );
  }

  const handleSend = (e) => {
    e.preventDefault();
    if (!inputText.trim()) return;
    onSendMessage(inputText);
    setInputText('');
  };

  // Get initials for the persona avatar (e.g. "Alex (Colleague)" → "A")
  const initial = persona.name.charAt(0).toUpperCase();

  return (
    <div className="chat-area">
      {/* ── Header ── */}
      <div className="chat-header">
        <div className="chat-header-left">
          <div className="chat-persona-avatar">{persona.avatar}</div>
          <div>
            <div className="chat-persona-name">{persona.name}</div>
            <div className="chat-persona-status">
              <span className="typing-dot" />
              {persona.status === 'typing' ? 'typing...' : persona.status === 'online' ? 'typing...' : persona.lastSeen}
            </div>
          </div>
        </div>

        <div className="chat-header-actions">
          <button className="icon-btn" title="Search"><Search size={15} /></button>
          <button className="icon-btn" title="More"><MoreVertical size={15} /></button>
          <button className="profile-btn" onClick={onToggleDashboard}>
            <Sparkles size={13} />
            <span>{showDashboard ? 'Collapse' : 'Clone Style Profile'}</span>
          </button>
        </div>
      </div>

      {/* ── Messages ── */}
      <div className="messages-area">
        {/* System banner */}
        <div className="sys-banner">
          🔒 Messages generated by local Llama 3.2. Style accuracy matches the clone's WhatsApp source profile.
        </div>

        {persona.chatHistory.map((msg, index) => {
          const isMe = msg.sender === 'me';
          return (
            <div key={msg.id || index} className={`msg-row ${isMe ? 'me' : 'them'}`}>
              {/* Avatar shown only for received messages */}
              {!isMe && (
                <div className="msg-sender-avatar">{initial}</div>
              )}

              <div className="msg-content">
                <div className={`msg-bubble ${isMe ? 'me' : 'them'}`}>
                  {msg.text}
                </div>
                <div className={`msg-meta ${isMe ? 'me' : 'them'}`}>
                  <span>{msg.timestamp}</span>
                  {isMe && (
                    msg.status === 'read'
                      ? <CheckCheck size={11} style={{ color: '#93c5fd' }} />
                      : <Check size={11} />
                  )}
                </div>
              </div>
            </div>
          );
        })}

        <div ref={messagesEndRef} />
      </div>

      {/* ── Input ── */}
      <form className="input-bar" onSubmit={handleSend}>
        <div className="InputContainer">
          <input
            type="text"
            className="input"
            placeholder="Type a message or trigger your digital clone..."
            value={inputText}
            onChange={e => setInputText(e.target.value)}
          />
        </div>
        <button type="submit" className="send-btn">
          <Send size={16} />
        </button>
      </form>
    </div>
  );
}
