import React, { useState, useEffect, useRef } from 'react';
import { Phone, Video, Search, MoreVertical, Smile, Paperclip, Send, Mic, Check, CheckCheck } from 'lucide-react';

export default function ChatWindow({ persona, onSendMessage, darkMode }) {
  const [inputText, setInputText] = useState('');
  const messagesEndRef = useRef(null);

  // Auto-scroll to bottom on messages change
  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [persona?.chatHistory]);

  if (!persona) {
    return (
      <div className={`flex-1 flex flex-col items-center justify-center p-8 text-center ${
        darkMode ? 'bg-[#222e35] text-whatsapp-dark-text-secondary' : 'bg-[#f8f9fa] text-gray-500'
      }`}>
        <div className="text-6xl mb-4">🤖</div>
        <h2 className="text-xl font-semibold mb-2">Digital Clone AI</h2>
        <p className="max-w-md text-sm leading-relaxed">
          Select a chat persona from the sidebar to start conversing with their digital clone, or upload a WhatsApp chat log in the style panel to train a new one.
        </p>
      </div>
    );
  }

  const handleSend = (e) => {
    e.preventDefault();
    if (!inputText.trim()) return;
    onSendMessage(inputText);
    setInputText('');
  };

  return (
    <div className={`flex-1 flex flex-col h-full border-r ${
      darkMode ? 'border-whatsapp-dark-border' : 'border-whatsapp-light-border'
    }`}>
      {/* Chat Header */}
      <div className={`px-4 py-3 flex items-center justify-between shadow-sm z-10 ${
        darkMode ? 'bg-[#202c33] text-whatsapp-dark-text-primary' : 'bg-[#f0f2f5] text-whatsapp-light-text-primary'
      }`}>
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-full bg-slate-200 dark:bg-slate-700 flex items-center justify-center text-xl shadow-sm flex-shrink-0">
            {persona.avatar}
          </div>
          <div>
            <h3 className="font-semibold text-sm leading-tight">{persona.name}</h3>
            <span className="text-[11px] text-emerald-500 dark:text-emerald-400 font-medium">
              {persona.status === 'online' ? 'typing...' : persona.lastSeen}
            </span>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex items-center gap-5 text-gray-500 dark:text-gray-400">
          <button title="Start Video Call" className="hover:text-emerald-500 transition-colors cursor-pointer">
            <Video size={18} />
          </button>
          <button title="Start Voice Call" className="hover:text-emerald-500 transition-colors cursor-pointer">
            <Phone size={18} />
          </button>
          <div className="w-px h-5 bg-gray-300 dark:bg-gray-700 mx-1"></div>
          <button title="Search in Chat" className="hover:text-emerald-500 transition-colors cursor-pointer">
            <Search size={18} />
          </button>
          <button title="Chat Menu" className="hover:text-emerald-500 transition-colors cursor-pointer">
            <MoreVertical size={18} />
          </button>
        </div>
      </div>

      {/* Message Screen (Scroll Pane) */}
      <div className="flex-1 overflow-y-auto p-4 space-y-3 whatsapp-doodle flex flex-col">
        {/* Helper System Info Banner */}
        <div className="self-center bg-amber-50 dark:bg-[#182229] border border-amber-200/50 dark:border-whatsapp-dark-border rounded-md px-3 py-1.5 text-[11px] text-amber-800 dark:text-amber-300 max-w-sm text-center shadow-sm">
          🔒 Messages generated by local Llama 3.2. Style accuracy matches the clone's WhatsApp source profile.
        </div>

        {persona.chatHistory.map((msg, index) => {
          const isMe = msg.sender === 'me';
          return (
            <div
              key={msg.id || index}
              className={`flex flex-col max-w-[70%] rounded-lg px-3 py-1.5 shadow-sm relative text-sm ${
                isMe
                  ? `${darkMode ? 'bg-whatsapp-dark-bubble-sent text-whatsapp-dark-text-primary' : 'bg-whatsapp-light-bubble-sent text-gray-800'} self-end rounded-tr-none`
                  : `${darkMode ? 'bg-whatsapp-dark-bubble-recv text-whatsapp-dark-text-primary' : 'bg-whatsapp-light-bubble-recv text-gray-800'} self-start rounded-tl-none`
              }`}
            >
              {/* Message text */}
              <p className="leading-relaxed break-words pr-12 pb-1">{msg.text}</p>
              
              {/* Message Time and Status Receipt */}
              <div className="absolute bottom-1 right-2 flex items-center gap-1 text-[9px] text-gray-400">
                <span>{msg.timestamp}</span>
                {isMe && (
                  <span>
                    {msg.status === 'read' ? (
                      <CheckCheck size={13} className="text-sky-400" />
                    ) : msg.status === 'delivered' ? (
                      <CheckCheck size={13} className="text-gray-400" />
                    ) : (
                      <Check size={13} className="text-gray-400" />
                    )}
                  </span>
                )}
              </div>
            </div>
          );
        })}
        <div ref={messagesEndRef} />
      </div>

      {/* Input Message Footer Bar */}
      <form onSubmit={handleSend} className={`p-3 flex items-center gap-3 ${
        darkMode ? 'bg-[#202c33]' : 'bg-[#f0f2f5]'
      }`}>
        <div className="flex items-center gap-3 text-gray-500 dark:text-gray-400">
          <button type="button" title="Emojis" className="hover:text-emerald-500 transition-colors cursor-pointer">
            <Smile size={22} />
          </button>
          <button type="button" title="Attach Document" className="hover:text-emerald-500 transition-colors cursor-pointer">
            <Paperclip size={22} />
          </button>
        </div>

        {/* Input box */}
        <input
          type="text"
          value={inputText}
          onChange={(e) => setInputText(e.target.value)}
          placeholder="Type a message or trigger your digital clone..."
          className={`flex-1 rounded-lg px-4 py-2.5 text-sm outline-none border-none shadow-inner ${
            darkMode 
              ? 'bg-[#2a3942] text-whatsapp-dark-text-primary placeholder-gray-500' 
              : 'bg-white text-gray-800 placeholder-gray-400'
          }`}
        />

        {/* Dynamic Action Button */}
        <div>
          {inputText.trim() ? (
            <button
              type="submit"
              className="w-10 h-10 rounded-full bg-emerald-600 hover:bg-emerald-500 text-white flex items-center justify-center transition-colors cursor-pointer shadow-md"
            >
              <Send size={18} />
            </button>
          ) : (
            <button
              type="button"
              title="Record Voice Note"
              className="w-10 h-10 rounded-full hover:bg-gray-200 dark:hover:bg-[#2a3942] text-gray-500 dark:text-gray-400 flex items-center justify-center transition-colors cursor-pointer"
            >
              <Mic size={20} />
            </button>
          )}
        </div>
      </form>
    </div>
  );
}
